---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.
```{r}
library("tidyverse")
library("janitor")
```

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`
```{r}
homerange <- readr::read_csv("data/Tamburelloetal_HomeRangeDatabase.csv", na="-999") %>% 
  clean_names()
glimpse(homerange)
```

2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.
```{r}
homerange %>% 
  group_by(class) %>% 
  summarize(min_mass = min(log10_mass),
            mean_mass = mean(log10_mass),
            max_mass = max(log10_mass))
```

```{r}
actino <- homerange %>% 
  filter(class == "actinopterygii") %>% 
  select(class,species, log10_mass)
actino
```


3. Make a plot that best summarizes this output.
```{r}
homerange %>% 
  ggplot(aes(x=class, y=log10_mass)) +
           geom_boxplot(na.rm = T) #show a range of values 
#the black line in the box is the median NOT mean
```

